# Generated by Django 6.0.1 on 2026-02-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nr_venda',
            new_name='vl_venda',
        ),
    ]
