# Generated by Django 6.0.4 on 2026-04-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produtos", "0004_remove_produto_cd_barras_remove_produto_estoque_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="dt_validade",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nr_custo_unitario",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nr_valor_ajuste",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nr_valor_desconto",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nr_valor_frete",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nr_valor_imposto",
        ),
        migrations.RemoveField(
            model_name="produto",
            name="nr_valor_total",
        ),
    ]
