# Generated by Django 6.0.1 on 2026-01-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, null=True)),
                ('liked', models.CharField(choices=[('sim', 'Gostou'), ('nao', 'Não gostou')], default='sim', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
