# Generated by Django 6.0.1 on 2026-01-31 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sugestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, null=True)),
                ('liked', models.CharField(choices=[('sim', 'Gostou'), ('nao', 'Não gostou')], default='sim', max_length=3)),
            ],
        ),
    ]
