# Generated by Django 6.0.1 on 2026-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sugestoes', '0002_sugestao_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestao',
            options={'ordering': ['-id'], 'verbose_name': 'sugestao', 'verbose_name_plural': 'sugestoes'},
        ),
        migrations.AlterModelTable(
            name='sugestao',
            table='sugestao',
        ),
    ]
