# Generated by Django 6.0.1 on 2026-01-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='is_finalizado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
