# Generated by Django 6.0.1 on 2026-02-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_alter_carro_nr_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carro',
            options={'ordering': ['-id'], 'verbose_name': 'carro', 'verbose_name_plural': 'carros'},
        ),
        migrations.AlterModelTable(
            name='carro',
            table='carro',
        ),
    ]
