name: CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: instalando pip-tools
        run: pip install pip-tools

      - name: Instalando as dependências
        run: pip install -r requirements/dev.txt

      - name: Rodando checagem de sintaxe
        run: ruff check .

      - name: Rodando checagem de formatação
        run: black --check .

      - name: Rodando testes
        run: pytest